name: Run Gradle and upload to build- or testserver on push

on:
  push:
    branches:
      - testserver
      - buildserver
      -
jobs:
  gradle:
    runs-on: ubuntu-latest
    environment: minelabs_upload
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_MINELABS_KEY }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Move build to output
        run: ./.github/scripts/move_build.sh
        shell: bash

      - name: Upload to minelabs.be
        if: github.ref == 'refs/heads/testserver'
        run: ./.github/scripts/sftp_upload.sh
        shell: bash
        env:
          SFTP_PORT: 2233

      - name: Upload to testserver.minelabs.be
        if: github.ref == 'refs/heads/buildserver'
        run: ./.github/scripts/sftp_upload.sh
        shell: bash
        env:
          SFTP_PORT: 2235

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: mod
          path: output

